SELECT * FROM COUNTRIES;

SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM EMPLOYEES
WHERE SALARY > 8000 AND DEPARTMENT_ID = 30;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%ne%';

SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '1993-01-01' AND '1994-12-31';


SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES
WHERE SALARY > 10000 AND (DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 80 OR DEPARTMENT_ID = 90);


