SELECT * FROM COUNTRIES;

SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM EMPLOYEES
WHERE SALARY > 8000 AND DEPARTMENT_ID = 30;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%ne%';

SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '1993-01-01' AND '1994-12-31';


SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES
WHERE SALARY > 10000 AND (DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 80 OR DEPARTMENT_ID = 90);


SELECT COUNTRY_NAME, REGION_NAME
FROM COUNTRIES
JOIN REGIONS
ON REGIONS.REGION_ID = COUNTRIES.REGION_ID;


SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_TITLE
FROM EMPLOYEES
JOIN JOBS
ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
WHERE DEPARTMENT_ID = 90;

SELECT DEPARTMENT_NAME, ROUND(AVG(SALARY), 2)
FROM DEPARTMENTS
JOIN EMPLOYEES
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME, MAX(SALARY) - MIN(SALARY)
FROM DEPARTMENTS
JOIN EMPLOYEES
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS
ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE DEPARTMENTS.DEPARTMENT_NAME = 'Finance';

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE LAST_NAME LIKE '%de%';



